### ISSUE TITLE
🧹 🧹 🧹 

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_TCA8418#3]
@tekktrik this library is ready to rock! you know what to do :)

**Comment by tekktrik** [comment]
Okie dokie!

**Comment by tekktrik** [comment]
Pending resolution of #4 before adding to bundle or RTD

**Comment by tekktrik** [comment]
@kattni ready for the RTD webhook!

**Comment by kattni** [comment]
Done!
