### ISSUE TITLE
Repository needs to be renamed

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_TCA8418#4]
Name should be `Adafruit_CircuitPython_TCA8418` (note the underscore)

**Comment by tekktrik** [comment]
@ladyada just a heads up, I think this also changes the `git` URL so if you come back to this it'll likely have changed.

**Comment by ladyada** [comment]
oh woops! yah no problem. btw github does URL forwarding so its ok! can always change names :)

**Comment by tekktrik** [comment]
Oh sweeeeet, perfect then!  Learning new things!

**Comment by tekktrik** [comment]
Resolved!
